version: "3.9"
services:
  api:
    container_name: todo-list-server
    build: .
    ports:
      - 8040:8040
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo
    container_name: todo-list-server-mongodb
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
volumes:
  db-data: